// Generated by CoffeeScript 1.6.3
define(["jquery", "vendor/mootit/riot"], function($, Riot) {
  var App;
  return App = (function() {
    function App() {
      console.log("constructed");
      $('.js-title').html("test");
    }

    App.prototype.start = function() {
      return console.log("started");
    };

    return App;

  })();
});
