// Generated by CoffeeScript 1.6.3
var requireConfig;

requireConfig = {
  baseUrl: 'scripts/',
  paths: {
    jquery: 'vendor/jquery/jquery-2.0.3'
  }
};

require.config(requireConfig);

define(['application/main', 'jquery'], function(App, $) {
  var app;
  app = new App();
  return app.start();
});
